### ISSUE TITLE
Failed to activate the run-lua package

### ISSUE THREAD

**Issue by Deph0** [dqsully/run-lua#1]
[Enter steps to reproduce below:]
1. ... install the package, ???, profit.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [run-lua](https://github.com/dqsully/run-lua) package, v0.0.7
### Stack Trace

Failed to activate the run-lua package

```
At View markup must have a single root element

Error: View markup must have a single root element
  at LuaOutput.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:160:17)
  at LuaOutput.ScrollView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
  at new LuaOutput (/Users/andreaskramer/.atom/packages/run-lua/lib/lua-output.coffee:16:5)
  at Object.module.exports.RunLua.activate (/Users/andreaskramer/.atom/packages/run-lua/lib/run-lua.coffee:16:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -1:48.7.0 core:close (atom-pane.pane.active)
     -1:11 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:07.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:03.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:39.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
run-lua, v0.0.7

# Dev
No dev packages
```

**Comment by dqsully** [comment]
I am a beginner to this, so I am trying to learn as fast as possible, but I have never worked with Space Pen, and had to publish the package to test it out, but it should be working by the end of today. I am also getting this error, and it is because I haven't correctly implemented the 'content' function of my custom view, but thank you for reporting! If you have any suggestions that would be great.
