### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by davidgarland** [dqsully/run-lua#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [run-lua](https://github.com/dqsully/run-lua) package, v0.2.0
### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /Users/johngarland/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:983

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (/Users/johngarland/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:983:15)
  at TextBuffer.module.exports.TextBuffer.save (/Users/johngarland/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Users/johngarland/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Object.module.exports.RunLua.executeCurrent (/Users/johngarland/.atom/packages/run-lua-master/lib/run-lua.coffee:29:40)
  at atom-workspace.subscriptions.add.atom.commands.add.run-lua:executeCurrent (/Users/johngarland/.atom/packages/run-lua-master/lib/run-lua.coffee:16:90)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/johngarland/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Users/johngarland/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/johngarland/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Users/johngarland/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -0:44.6.0 run-lua:executeCurrent (atom-text-editor.editor.is-focused)
  2x -0:28.4.0 encoding-selector:show (atom-text-editor.editor)
     -0:20.5.0 grammar-selector:show (atom-text-editor.editor)
  2x -0:11.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:backspace (atom-text-editor.editor.is-focused)
  7x -0:06.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:06.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.6.0 run-lua:executeCurrent (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by dqsully** [comment]
Thank you for reporting this, I forgot to account for running a lua script that does not yet exist on the disk, which is what caused this error. I will release a fix shortly.

**Comment by dqsully** [comment]
When you update my package, you will need to reload Atom for the changes to take effect.
